### ISSUE TITLE
flake8 5 compat

### ISSUE THREAD

**Issue by christianbundy** [adamchainz/flake8-no-pep420#133]
### Python Version

3.10

### flake8 Version

5.0.2

### Package Version

2.3.0

### Description

Problem: This package won't allow me to upgrade to flake8 5.x.x+ because of a dependency constraint.

Solution: I see https://github.com/adamchainz/flake8-no-pep420/commit/5088caead3b6920da48577ce4f4e04b8ef695a50 in `master`, can we release that?

**Comment by christianbundy** [comment]
nvm pretty sure I'm an idiot and I'm using version 1.1 -- sorry for the noise!

**Comment by adamchainz** [comment]
please close issue in future

**Comment by christianbundy** [comment]
Oops, thought I'd pressed 'comment and close'. Thanks for closing.
